[package]
name = "oxygen"
version = "0.1.0"
authors = ["Paulo <elie9alb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seahorse = "1.1"
